---
- name: jenkins
  box: centos/7
  cpus: 1
  memory: 4096
  private_ip: 10.0.10.10
  packages_manager: yum
  packages:
  - wget 
  - unzip
  - git
  scripts:
    startup
- name: server
  box: centos/7
  cpus: 1
  memory: 1024
  private_ip: 10.0.10.11
  packages_manager: yum
  packages:
  - wget
  - unzip
  - git
  scripts:
    startup
...
